language: shell

services:
  - docker

notifications:
  email: false

script:
  - sudo apt-get install python3-pip python3-setuptools python3-wheel -y
  - python3 -m pip install --upgrade pip
  - python3 -m pip install wheel
  - python3 -m pip install jsonschema
  - python3 -m pip install PyEmail
  - python3 -m pip install click
  - python3 tools/indexing.py
  - cat index_all.json
  - docker pull summergift/csp_test:v1.0
  - docker run -v "`pwd`:/rt-thread/sdk-index" -it summergift/csp_test:v1.0 bash -c "python /rt-thread/sdk-index/tools/csp_check/csp_check.py"
  - cd tools/csp_check
  - python3 mail_send.py
